name: Pavlovi
favicon: null
layout_spectrum: 0.6220343671739101
typography_spectrum: 0.3490557053592056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.44887306378223
  lightness: 0.18242953508161008
  saturation: 0.1348853048402816
  rhythmicContrast: 0.8002282560337335
purpose: []
